  CREATE TABLE "AUDIT_LOG" 
   (	"LOG_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(50), 
	"ACTION_TYPE" VARCHAR2(20), 
	"RECORD_ID" NUMBER, 
	"CHANGED_BY" VARCHAR2(100), 
	"CHANGE_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"DETAILS" VARCHAR2(4000), 
	 PRIMARY KEY ("LOG_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "BOOKING" 
   (	"BOOKING_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"QUANTITY" NUMBER(3,0) NOT NULL ENABLE, 
	"USER_ID" NUMBER(10,0), 
	"TICKET_ID" NUMBER(10,0), 
	 CONSTRAINT "BOOKING_PK" PRIMARY KEY ("BOOKING_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EVENT" 
   (	"EVENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(100) NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(100) NOT NULL ENABLE, 
	"EVENT_DATE" DATE NOT NULL ENABLE, 
	"CAPACITY" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "EVENT_PK" PRIMARY KEY ("EVENT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PAYMENT" 
   (	"PAYMENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AMOUNT" NUMBER(6,0) NOT NULL ENABLE, 
	"PAYMENT_DATE" DATE NOT NULL ENABLE, 
	"BOOKING_ID" NUMBER(10,0), 
	 CONSTRAINT "PAYMENT_PK" PRIMARY KEY ("PAYMENT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "TICKET" 
   (	"TICKET_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"PRICE" NUMBER(6,0) NOT NULL ENABLE, 
	"EVENT_ID" NUMBER(10,0), 
	 CONSTRAINT "TICKET_PK" PRIMARY KEY ("TICKET_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "User" 
   (	"USER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PASSWORD_HASH" VARCHAR2(200) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100), 
	"ROLE" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "USER_USERNAME_UN" UNIQUE ("USERNAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_USER_ROLE" CHECK (role IN ('ADMIN','ATTENDEE','ORGANIZER')) ENABLE
   ) ;

  ALTER TABLE "BOOKING" ADD CONSTRAINT "BOOKING_TICKET_FK" FOREIGN KEY ("TICKET_ID")
	  REFERENCES "TICKET" ("TICKET_ID") ENABLE;
  ALTER TABLE "BOOKING" ADD CONSTRAINT "BOOKING_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "User" ("USER_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BOOKING_BOOKING_ID_TRG" 
BEFORE INSERT ON Booking 
FOR EACH ROW 
 WHEN (NEW.booking_id IS NULL) BEGIN 
    :NEW.booking_id := Booking_booking_id_SEQ.NEXTVAL; 
END;
/
ALTER TRIGGER "BOOKING_BOOKING_ID_TRG" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_AUDIT_LOG" 
AFTER INSERT OR UPDATE OR DELETE ON Booking
FOR EACH ROW
DECLARE
    v_user        VARCHAR2(100);
    v_action      VARCHAR2(20);
    v_record_id   NUMBER;
    v_details     VARCHAR2(4000);
BEGIN
    v_user := NVL(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        v_action    := 'INSERT';
        v_record_id := :NEW.booking_id;
        v_details   := 'New booking created for ticket ID: ' || :NEW.ticket_id || ' with quantity: ' || :NEW.quantity;
    ELSIF UPDATING THEN
        v_action    := 'UPDATE';
        v_record_id := :NEW.booking_id;
        v_details   := 'Quantity altered from ' || :OLD.quantity || ' to ' || :NEW.quantity;
    ELSIF DELETING THEN
        v_action    := 'DELETE';
        v_record_id := :OLD.booking_id;
        v_details   := 'Booking removed. Was previously for ticket ID: ' || :OLD.ticket_id;
    END IF;

    INSERT INTO Audit_Log (table_name, action_type, record_id, changed_by, details) 
    VALUES ('BOOKING', v_action, v_record_id, v_user, v_details);
END;
/
ALTER TRIGGER "TRG_AUDIT_LOG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "EVENT_EVENT_ID_TRG" 
BEFORE INSERT ON Event 
FOR EACH ROW 
 WHEN (NEW.event_id IS NULL) BEGIN 
    :NEW.event_id := Event_event_id_SEQ.NEXTVAL; 
END;
/
ALTER TRIGGER "EVENT_EVENT_ID_TRG" ENABLE;

  ALTER TABLE "PAYMENT" ADD CONSTRAINT "PAYMENT_BOOKING_FK" FOREIGN KEY ("BOOKING_ID")
	  REFERENCES "BOOKING" ("BOOKING_ID") ON DELETE CASCADE ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PAYMENT_PAYMENT_ID_TRG" 
BEFORE INSERT ON Payment 
FOR EACH ROW 
 WHEN (NEW.payment_id IS NULL) BEGIN 
    :NEW.payment_id := Payment_payment_id_SEQ.NEXTVAL; 
END;
/
ALTER TRIGGER "PAYMENT_PAYMENT_ID_TRG" ENABLE;

  ALTER TABLE "TICKET" ADD CONSTRAINT "TICKET_EVENT_FK" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "EVENT" ("EVENT_ID") ON DELETE CASCADE ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TICKET_TICKET_ID_TRG" 
BEFORE INSERT ON Ticket 
FOR EACH ROW 
 WHEN (NEW.ticket_id IS NULL) BEGIN 
    :NEW.ticket_id := Ticket_ticket_id_SEQ.NEXTVAL; 
END;
/
ALTER TRIGGER "TICKET_TICKET_ID_TRG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "USER_USER_ID_TRG" 
BEFORE INSERT ON "User" 
FOR EACH ROW 
 WHEN (NEW.user_id IS NULL) BEGIN 
    :NEW.user_id := User_user_id_SEQ.NEXTVAL; 
END;
/
ALTER TRIGGER "USER_USER_ID_TRG" ENABLE;
create or replace FUNCTION app_user_auth (
    p_username IN VARCHAR2,
    p_password IN VARCHAR2
) RETURN BOOLEAN IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM "User"
     WHERE UPPER("USERNAME") = UPPER(p_username)
       AND "PASSWORD_HASH" = p_password;

    IF v_count > 0 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RETURN FALSE;
END;
/
create or replace FUNCTION func_authenticate_user (
    p_username IN VARCHAR2,
    p_password IN VARCHAR2
) RETURN BOOLEAN
IS
    v_stored_hash VARCHAR(255);
BEGIN
    SELECT password_hash
    INTO v_stored_hash
    FROM "User"
    WHERE LOWER(TRIM(username)) = LOWER(TRIM(p_username))
    OR LOWER(TRIM(email)) = LOWER(TRIM(p_username));

    IF v_stored_hash = func_hash_password(p_password) THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RETURN FALSE;
END func_authenticate_user;
/
create or replace FUNCTION func_hash_password (
    p_password IN VARCHAR2
) RETURN VARCHAR2
IS
    v_hash VARCHAR(255);
BEGIN
    IF p_password IS NULL THEN
        RETURN NULL;
    END IF;

    SELECT LOWER(RAWTOHEX(STANDARD_HASH(p_password,'SHA256')))
        INTO v_hash
        FROM DUAL;

    RETURN v_hash;
END func_hash_password;
/
create or replace FUNCTION FUNC_TOTAL_REVENUE (
    p_event_id IN NUMBER
) RETURN NUMBER AS
    v_total_revenue NUMBER := 0;
BEGIN
    SELECT NVL(SUM(b.quantity * t.price), 0) INTO v_total_revenue
    FROM Booking b
    JOIN Ticket t ON b.ticket_id = t.ticket_id
    WHERE t.event_id = p_event_id;

    RETURN v_total_revenue;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END FUNC_TOTAL_REVENUE;
/




























  CREATE UNIQUE INDEX "USER_PK" ON "User" ("USER_ID") 
  ;

  CREATE UNIQUE INDEX "EVENT_PK" ON "EVENT" ("EVENT_ID") 
  ;

  CREATE UNIQUE INDEX "USER_USERNAME_UN" ON "User" ("USERNAME") 
  ;

  CREATE UNIQUE INDEX "SYS_C00199980088" ON "AUDIT_LOG" ("LOG_ID") 
  ;

  CREATE UNIQUE INDEX "PAYMENT_PK" ON "PAYMENT" ("PAYMENT_ID") 
  ;

  CREATE UNIQUE INDEX "TICKET_PK" ON "TICKET" ("TICKET_ID") 
  ;

  CREATE UNIQUE INDEX "BOOKING_PK" ON "BOOKING" ("BOOKING_ID") 
  ;











create or replace PROCEDURE PROC_BOOK_TICKET (
    p_user_id   IN NUMBER,
    p_ticket_id IN NUMBER,
    p_quantity  IN NUMBER
) AS
    v_event_id        NUMBER;
    v_capacity        NUMBER;
    v_tickets_booked  NUMBER;
    v_tickets_left    NUMBER;
    v_user_email      VARCHAR2(100);
    v_event_title     VARCHAR2(100);
    v_booking_id      NUMBER;
BEGIN
    -- 1. Retrieve Event details (ID, Capacity, Title)
    SELECT event_id INTO v_event_id 
      FROM Ticket 
     WHERE ticket_id = p_ticket_id;
     
    SELECT capacity, title INTO v_capacity, v_event_title 
      FROM Event 
     WHERE event_id = v_event_id;

    -- 2. Retrieve User Email for notification
    SELECT email INTO v_user_email 
      FROM "User" 
     WHERE user_id = p_user_id;

    -- 3. Calculate remaining tickets
    SELECT NVL(SUM(b.quantity), 0) INTO v_tickets_booked
      FROM Booking b
      JOIN Ticket t ON b.ticket_id = t.ticket_id
     WHERE t.event_id = v_event_id;

    v_tickets_left := v_capacity - v_tickets_booked;

    -- 4. Validations
    IF p_quantity <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Quantity must be greater than zero.');
    ELSIF v_tickets_left < p_quantity THEN
        RAISE_APPLICATION_ERROR(-20002, 'Booking failed: Not enough tickets available. Only ' || v_tickets_left || ' left.');
    ELSE
        -- 5. Insert Booking and capture the generated booking_id
        INSERT INTO Booking (quantity, user_id, ticket_id) 
        VALUES (p_quantity, p_user_id, p_ticket_id)
        RETURNING booking_id INTO v_booking_id;

        -- 6. Send Email Notification via APEX_MAIL
        IF v_user_email IS NOT NULL THEN
            APEX_MAIL.SEND(
                p_to   => v_user_email,
                p_from => 'noreply@atu.edu.gh',
                p_subj => 'Booking Confirmation - ' || v_event_title,
                p_body => 'Hello,' || CHR(10) || CHR(10) ||
                          'Your booking (ID: ' || v_booking_id || ') for "' || v_event_title || 
                          '" has been successfully created.' || CHR(10) ||
                          'Quantity: ' || p_quantity || CHR(10) || CHR(10) ||
                          'Thank you for using ATU ETMS!'
            );
            
            -- Push queued mail immediately
            APEX_MAIL.PUSH_QUEUE();
        END IF;

        COMMIT;
    END IF;
END PROC_BOOK_TICKET;
/
create or replace PROCEDURE PROC_CREATE_EVENT (
    p_title      IN VARCHAR2,
    p_location   IN VARCHAR2,
    p_event_date IN DATE,
    p_capacity   IN NUMBER
) AS
BEGIN
    -- Business Rule Validation: Check capacity and date
    IF p_capacity <= 0 THEN
        RAISE_APPLICATION_ERROR(-20005, 'Event capacity must be greater than zero.');
    ELSIF p_event_date < SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20006, 'Event date cannot be set in the past.');
    ELSE
        -- Insert the event record
        INSERT INTO Event (
            event_id,
            title,
            location,
            event_date,
            capacity
        ) VALUES (
            NULL, -- Handled by database identity or sequence
            p_title,
            p_location,
            p_event_date,
            p_capacity
        );
        
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Event created successfully!');
    END IF;
END PROC_CREATE_EVENT;
/



















   CREATE SEQUENCE  "BOOKING_BOOKING_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 125 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "EVENT_EVENT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "PAYMENT_PAYMENT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 96 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "TICKET_TICKET_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "USER_USER_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 118 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

























create or replace TRIGGER Booking_booking_id_TRG 
BEFORE INSERT ON Booking 
FOR EACH ROW 
WHEN (NEW.booking_id IS NULL) 
BEGIN 
    :NEW.booking_id := Booking_booking_id_SEQ.NEXTVAL; 
END;
/
create or replace TRIGGER Event_event_id_TRG 
BEFORE INSERT ON Event 
FOR EACH ROW 
WHEN (NEW.event_id IS NULL) 
BEGIN 
    :NEW.event_id := Event_event_id_SEQ.NEXTVAL; 
END;
/
create or replace TRIGGER Payment_payment_id_TRG 
BEFORE INSERT ON Payment 
FOR EACH ROW 
WHEN (NEW.payment_id IS NULL) 
BEGIN 
    :NEW.payment_id := Payment_payment_id_SEQ.NEXTVAL; 
END;
/
create or replace TRIGGER Ticket_ticket_id_TRG 
BEFORE INSERT ON Ticket 
FOR EACH ROW 
WHEN (NEW.ticket_id IS NULL) 
BEGIN 
    :NEW.ticket_id := Ticket_ticket_id_SEQ.NEXTVAL; 
END;
/
create or replace TRIGGER TRG_AUDIT_LOG
AFTER INSERT OR UPDATE OR DELETE ON Booking
FOR EACH ROW
DECLARE
    v_user        VARCHAR2(100);
    v_action      VARCHAR2(20);
    v_record_id   NUMBER;
    v_details     VARCHAR2(4000);
BEGIN
    v_user := NVL(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        v_action    := 'INSERT';
        v_record_id := :NEW.booking_id;
        v_details   := 'New booking created for ticket ID: ' || :NEW.ticket_id || ' with quantity: ' || :NEW.quantity;
    ELSIF UPDATING THEN
        v_action    := 'UPDATE';
        v_record_id := :NEW.booking_id;
        v_details   := 'Quantity altered from ' || :OLD.quantity || ' to ' || :NEW.quantity;
    ELSIF DELETING THEN
        v_action    := 'DELETE';
        v_record_id := :OLD.booking_id;
        v_details   := 'Booking removed. Was previously for ticket ID: ' || :OLD.ticket_id;
    END IF;

    INSERT INTO Audit_Log (table_name, action_type, record_id, changed_by, details) 
    VALUES ('BOOKING', v_action, v_record_id, v_user, v_details);
END;
/
create or replace TRIGGER User_user_id_TRG 
BEFORE INSERT ON "User" 
FOR EACH ROW 
WHEN (NEW.user_id IS NULL) 
BEGIN 
    :NEW.user_id := User_user_id_SEQ.NEXTVAL; 
END;
/